import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coloring Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl mt-20 text-center text-gray-600">
        COLORING BOOK
      </div>
    </div>
  );
}
