import Head from "next/head";
import { useEffect, useState } from "react";
import ArtWork from "../assets/svgs/art.svg";
import { colors } from "../assets/data/colors";
import SVGWrapper from "../components/SVGWrapper";
import Button from "../components/common/Button";

export default function Home() {
  const [selectedColor, setSelectedColor] = useState("#ff00dd");

  const updateColor = (element, color) => {
    element.setAttribute("fill", color ? color : selectedColor);
  };
  useEffect(() => {
    const paths = document.getElementsByTagName("path");
    console.log(paths);
    for (let i = 0; i < paths?.length; i++) {
      paths[i].classList.add("cursor-pointer");
      paths[i].addEventListener("click", () => {
        console.log("run");
        updateColor(paths[i]);
      });
    }
    return () => {
      for (let i = 0; i < paths?.length; i++) {
        paths[i].removeEventListener("click", () => {
          console.log(paths[i], "remove");
        });
      }
    };
  }, []);

  const fillWithRandomColors = () => {
    const paths = document.getElementsByTagName("path");
    for (let i = 0; i < paths?.length; i++) {
      var randomNum = Math.floor(Math.random() * colors.length + 1);
      console.log(paths[i].getAttribute("stroke"));
      updateColor(paths[i], colors[randomNum]);
    }
  };
  const clearColors = () => {
    const paths = document.getElementsByTagName("path");
    for (let i = 0; i < paths?.length; i++) {
      updateColor(paths[i], "#FFFFFF");
    }
  };
  return (
    <div>
      <Head>
        <title>Coloring Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SVGWrapper>
        <ArtWork />
      </SVGWrapper>
      <div className="w-1/2 flex flex-row justify-center self-center">
        <div className="flex flex-col rounded-md bg-gray-500">
          <div className="bg-black text-white px-2 w-full mx-3 rounded-lg"></div>
        </div>
      </div>
      <div className="flex flex-row gap-4 justify-center m-4">
        <Button text="CLEAR COLOR" onClick={clearColors} />
        <Button text="RANDOM COLOR" onClick={fillWithRandomColors} />
      </div>
    </div>
  );
}
